function SimulationNotice() {
  return (
    <div className="simulation-notice" role="note">
      <span className="notice-icon" aria-hidden="true">i</span>
      <span><strong>SIMULATED PROCESS MONITORING</strong><small>Process readings are generated by the model from the registered inputs and engineering assumptions. No industrial sensors are connected; these values are not measured plant data.</small></span>
    </div>
  )
}

export default SimulationNotice
